const config = require("../config");
const { httpError } = require("../helpers/errors");

let transcriptModulePromise = null;

async function getTranscriptModule() {
  if (!transcriptModulePromise) {
    transcriptModulePromise = import("youtube-transcript-plus");
  }
  return transcriptModulePromise;
}

function parseYouTubeVideoId(url) {
  const raw = String(url || "").trim();
  if (!raw) return null;

  if (/^[\w-]{11}$/.test(raw)) return raw;

  try {
    const u = new URL(raw);
    const host = u.hostname.replace(/^www\./, "");

    if (host === "youtu.be") {
      const id = u.pathname.split("/").filter(Boolean)[0];
      return id && /^[\w-]{11}$/.test(id) ? id : null;
    }

    if (host === "youtube.com" || host === "m.youtube.com") {
      const v = u.searchParams.get("v");
      if (v && /^[\w-]{11}$/.test(v)) return v;

      const parts = u.pathname.split("/").filter(Boolean);
      const marker = parts[0];
      const id = parts[1];
      if (["shorts", "embed", "live"].includes(marker) && id && /^[\w-]{11}$/.test(id)) {
        return id;
      }
    }
  } catch {
    /* invalid URL */
  }

  return null;
}

function mapTranscriptError(err, videoId) {
  const name = err?.name || "";
  if (name === "YoutubeTranscriptInvalidVideoIdError") {
    return httpError(400, "Invalid YouTube URL. Use a watch, shorts, or youtu.be link.");
  }
  if (name === "YoutubeTranscriptVideoUnavailableError") {
    return httpError(400, "YouTube video is unavailable or private.");
  }
  if (name === "YoutubeTranscriptDisabledError") {
    return httpError(
      400,
      "Captions are disabled for this video. Try another video or paste the transcript as text."
    );
  }
  if (name === "YoutubeTranscriptNotAvailableError") {
    return httpError(
      400,
      "No captions found for this video. Enable captions on YouTube or paste the transcript as text."
    );
  }
  if (name === "YoutubeTranscriptNotAvailableLanguageError") {
    const langs = err.availableLangs?.join(", ") || "unknown";
    return httpError(
      400,
      `Captions not available in the requested language for video ${videoId}. Available: ${langs}`
    );
  }
  if (name === "YoutubeTranscriptTooManyRequestError") {
    return httpError(429, "YouTube rate-limited transcript fetch. Wait a minute and try again.");
  }
  return httpError(502, `Failed to fetch YouTube transcript: ${err.message}`);
}

async function pickLanguage(videoId, langs, mod) {
  let available = [];
  try {
    available = await mod.listLanguages(videoId, { retries: 1 });
  } catch {
    return langs[0] || "en";
  }

  if (!available.length) return langs[0] || "en";

  const codes = available.map((t) => t.languageCode);
  for (const preferred of langs) {
    if (codes.includes(preferred)) return preferred;
    const base = preferred.split("-")[0];
    const match = codes.find((c) => c === base || c.startsWith(`${base}-`));
    if (match) return match;
  }

  const manual = available.find((t) => !t.isAutoGenerated);
  return manual?.languageCode || available[0].languageCode;
}

/**
 * Fetch YouTube video title + full caption transcript for knowledge ingest.
 */
async function fetchYouTubeTranscript(url) {
  const videoId = parseYouTubeVideoId(url);
  if (!videoId) {
    throw httpError(400, "Invalid YouTube URL. Use a watch, shorts, or youtu.be link.");
  }

  const mod = await getTranscriptModule();
  const { fetchTranscript, toPlainText } = mod;
  const langs = config.youtube.transcriptLangs;
  const lang = await pickLanguage(videoId, langs, mod);

  let result;
  try {
    result = await fetchTranscript(url, {
      lang,
      videoDetails: true,
      retries: 2,
      retryDelay: 1000,
    });
  } catch (err) {
    if (err?.name === "YoutubeTranscriptNotAvailableLanguageError" && langs.length > 1) {
      try {
        result = await fetchTranscript(url, {
          videoDetails: true,
          retries: 2,
          retryDelay: 1000,
        });
      } catch (retryErr) {
        throw mapTranscriptError(retryErr, videoId);
      }
    } else {
      throw mapTranscriptError(err, videoId);
    }
  }

  const segments = result.segments || result;
  const title = result.videoDetails?.title || null;
  const text = toPlainText(segments).replace(/\s+/g, " ").trim();

  if (!text || text.length < 40) {
    throw httpError(
      400,
      "Transcript was too short or empty. The video may have no usable captions."
    );
  }

  const channel = result.videoDetails?.author || null;
  const header = [
    title ? `Video: ${title}` : `YouTube video: ${videoId}`,
    channel ? `Channel: ${channel}` : null,
    `Source: ${url}`,
    `Caption language: ${lang}`,
  ]
    .filter(Boolean)
    .join("\n");

  return {
    videoId,
    title,
    channel,
    language: lang,
    segmentCount: segments.length,
    text: `${header}\n\n${text}`,
  };
}

module.exports = {
  parseYouTubeVideoId,
  fetchYouTubeTranscript,
};
